name: ResKAN
channels:
  - nvidia
  - pytorch
dependencies:
  - cuda-toolkit=12.*
  - einops
  - gcc=12.*
  - gxx=12.*
  - ipykernel
  - ipywidgets
  - lightning
  - python=3.12.*
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - wandb
